# The following two variable will be commandline determined by TA
# For testing, you could uncomment them.
SRIPATH ?= /tmp2/b03902048/dsp_hw3/srilm-1.5.10
MACHINE_TYPE ?= i686-m64
LM ?= bigram.lm

CXX = g++
CXXFLAGS = -O3 -I$(SRIPATH)/include -w
vpath lib%.a $(SRIPATH)/lib/$(MACHINE_TYPE)

TARGET = mydisambig
SRC = mydisambig.cpp
OBJ = $(SRC:.cpp=.o)
TO = ZhuYin-Big5.map
FROM = Big5-ZhuYin.map
.PHONY: all clean map run

all: $(TARGET)

$(TARGET): $(OBJ) -loolm -ldstruct -lmisc
	$(CXX) $(LDFLAGS) -o $@ $^

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $<
run:
	#TODO How to run your code toward different txt? 
	for i in $(shell seq 1 10) ; do \
		echo "Running $$i.txt"; \
		./mydisambig -text testdata/$$i.txt -map $(TO) -lm $(LM) -order 2 > result2/$$i.txt; \
	done;
run_srilm:
	for i in $(shell seq 1 10) ; do \
		echo "Running $$i.txt by srilm/disambig"; \
		../srilm-1.5.10_i686-m64/disambig -text testdata/$$i.txt -map $(TO) -lm $(LM) -order 2 > result1/$$i.txt; \
	done;
map:
	#TODO How to map?
	echo "Mapping!"
	python mapping.py $(FROM) $(TO)
clean:
	$(RM) $(OBJ) $(TARGET)

